
server:
  port: 12000
spring:
  application:
    name: rabbitmq-source
  cloud:
    stream:
      bindings:
        input:
          destination: source-stream-input
          binder: rabbitmq
        output:
          destination: source-stream-output
          group: source-group
          binder: rabbitmq
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest